site_name: Deep Point Cloud Benchmark
nav:
nav:
    - Home: index.md
    - Introduction by Example: how_to_do/how_to_do.md
    
    - Core: src/core.md
    - Models: src/models.md
    - Datasets: src/datasets.md
    - Modules: src/modules.md
    
    - Logging: src/logging_visualization.md
    - Visualization: src/visualization.md
    - Utils: src/utils.md
theme: readthedocs

